In [ ]:
import numpy as np

### **Knapsack DP**

In [ ]:
weight=8
profits=np.array([2,3,4,1])
weights=np.array([3,4,5,6])
items=np.zeros(weights.shape[0])
rows=weights.shape[0]

In [ ]:
matrix=np.zeros((rows+1,weight+1))
matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
for i in range(1, rows+1):
  for j in range(1, weight+1):
    weight_index= j - weights[i-1]
    if weight_index < 0:
      matrix[i,j] = matrix[i-1,j]
    else:
      matrix[i,j] = max(matrix[i-1,j], (matrix[i-1, weight_index] + profits[i-1]))

In [ ]:
matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 2., 2., 2., 2., 2., 2.],
       [0., 0., 0., 2., 3., 3., 3., 5., 5.],
       [0., 0., 0., 2., 3., 4., 4., 5., 6.],
       [0., 0., 0., 2., 3., 4., 4., 5., 6.]])

In [ ]:
max_value=matrix[rows,weight]

In [ ]:
max_value

6.0

In [ ]:
j = weight
i = rows
while i != 0:        
  if matrix[i,j] != matrix[i-1, j]:
    items[i-1] = 1
    j -= weights[i - 1]
  i -= 1

In [ ]:
items

array([1., 0., 1., 0.])

## **Fibonacci DP**

In [ ]:
result = 0
num1 = 1
num2 = 1
for i in range(2, 8):
  result = num1 + num2
  num1=num2
  num2=result
result

21